api_key = "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"

[my_mongodb_credentials]
mongodb_connection_string = "mongodb+srv://team3535:seongmin@cluster0.swti5vl.mongodb.net/?retryWrites=true&w=majority"
database_name = "team3535"
collection_name_faq = "faq"